<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSHDhxe7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSHDhxe7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSHDhxe7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSHDhxe7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSHDhxe7\App_KernelDevDebugContainer([
    'container.build_hash' => 'SHDhxe7',
    'container.build_id' => '6df73395',
    'container.build_time' => 1605609299,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSHDhxe7');
